import { Router } from 'express';
import { AuthController } from '../controllers/auth.controller';
import { ProductController } from '../controllers/product.controller';
import { OrderController } from '../controllers/order.controller';
import { PaymentController } from '../controllers/payment.controller';
import { CategoryController } from '../controllers/category.controller';
import { PageController } from '../controllers/page.controller';
import { SettingsController } from '../controllers/settings.controller';
import { HomeController } from '../controllers/home.controller';
import { MailController } from '../controllers/mail.controller';
import { AnalyticsController } from '../controllers/analytics.controller';
import { authMiddleware, adminMiddleware, optionalAuthMiddleware } from '../middleware/auth.middleware';
import { uploadSingle, uploadMultiple } from '../middleware/upload.middleware';

const router = Router();

router.post('/login', AuthController.login);
router.post('/logout', AuthController.logout);
router.post('/register', AuthController.register);
router.get('/me', optionalAuthMiddleware, AuthController.me);
router.get('/profile', authMiddleware, AuthController.getProfile);
router.put('/profile', authMiddleware, AuthController.updateProfile);
router.post('/set-title', authMiddleware, adminMiddleware, SettingsController.setTitle);
router.post('/change-password', authMiddleware, AuthController.changePassword);
router.get('/users', authMiddleware, adminMiddleware, AuthController.getUsers);
router.get('/products', ProductController.getProducts);
router.get('/products/:id', ProductController.getProduct);
router.post('/products', authMiddleware, adminMiddleware, ProductController.addProduct);
router.put('/products/:id', authMiddleware, adminMiddleware, ProductController.updateProduct);
router.delete('/products/:id', authMiddleware, adminMiddleware, ProductController.deleteProduct);
router.post('/save-products-order', authMiddleware, adminMiddleware, ProductController.saveProductsOrder);
router.post('/upload-media', authMiddleware, adminMiddleware, uploadSingle('file'), ProductController.uploadMedia);
router.post('/add-product-images', authMiddleware, adminMiddleware, uploadMultiple('additional_images', 20), ProductController.addProductImages);
router.delete('/delete-product-image', authMiddleware, adminMiddleware, ProductController.deleteProductImage);
router.post('/generate-description', authMiddleware, adminMiddleware, ProductController.generateDescription);
router.post('/product-visibility', authMiddleware, adminMiddleware, ProductController.changeVisibility);
router.get('/categories', CategoryController.getAll);
router.post('/categories', authMiddleware, adminMiddleware, CategoryController.create);
router.put('/categories/:id', authMiddleware, adminMiddleware, CategoryController.update);
router.delete('/categories/:id', authMiddleware, adminMiddleware, CategoryController.delete);
router.post('/save-categories-order', authMiddleware, adminMiddleware, CategoryController.saveOrder);
router.post('/orders', OrderController.createOrder);
router.get('/orders', authMiddleware, adminMiddleware, OrderController.getOrders);
router.post('/update-order-status', authMiddleware, adminMiddleware, OrderController.updateOrderStatus);
router.post('/update-payment-status', authMiddleware, adminMiddleware, OrderController.updatePaymentStatus);
router.delete('/orders', authMiddleware, adminMiddleware, OrderController.deleteOrder);
router.get('/cleanup-orders', OrderController.cleanupOldOrders);
router.post('/payment', PaymentController.getPaymentToken);
router.post('/payment-notification', PaymentController.paymentNotification);
router.get('/pages', PageController.getAll);
router.get('/page-by-slug', PageController.getBySlug);
router.post('/pages', authMiddleware, adminMiddleware, PageController.create);
router.put('/pages/:id', authMiddleware, adminMiddleware, PageController.update);
router.delete('/pages/:id', authMiddleware, adminMiddleware, PageController.delete);
router.get('/page-navigation', PageController.getNavigation);
router.get('/home-content', HomeController.getAll);
router.post('/save-home-content', authMiddleware, adminMiddleware, HomeController.save);
router.get('/page-blocks', PageController.getBlocks);
router.get('/hero-image', PageController.getHeroImage);
router.post('/page-blocks', authMiddleware, adminMiddleware, PageController.createBlock);
router.put('/page-blocks/:id', authMiddleware, adminMiddleware, PageController.updateBlock);
router.delete('/page-blocks/:id', authMiddleware, adminMiddleware, PageController.deleteBlock);
router.post('/save-blocks-order', authMiddleware, adminMiddleware, PageController.updateBlocksOrder);
router.get('/params', SettingsController.getAll);
router.post('/save-params', authMiddleware, adminMiddleware, SettingsController.save);
router.post('/upload-logo', authMiddleware, adminMiddleware, uploadSingle('logo'), SettingsController.uploadLogo);
router.delete('/delete-logo', authMiddleware, adminMiddleware, SettingsController.deleteLogo);
router.post('/upload-background', authMiddleware, adminMiddleware, uploadSingle('image'), SettingsController.uploadBackground);
router.get('/theme-colors', SettingsController.getThemeColors);
router.post('/save-colors', authMiddleware, adminMiddleware, SettingsController.saveThemeColors);
router.post('/reset-colors', authMiddleware, adminMiddleware, SettingsController.resetThemeCss);
router.get('/theme-css', authMiddleware, adminMiddleware, SettingsController.getThemeCss);
router.post('/save-theme-css', authMiddleware, adminMiddleware, SettingsController.saveThemeCss);
router.post('/contact', MailController.send);
router.get('/messages', authMiddleware, adminMiddleware, MailController.getMessages);
router.delete('/messages/:id', authMiddleware, adminMiddleware, MailController.deleteMessage);
router.post('/send-reply', authMiddleware, adminMiddleware, MailController.sendReply);
router.get('/message-replies', authMiddleware, adminMiddleware, MailController.getReplies);
router.get('/analytics', authMiddleware, adminMiddleware, AnalyticsController.get);
router.get('/product-options', ProductController.getOptions);
router.post('/save-product-options', authMiddleware, adminMiddleware, ProductController.saveOptions);
router.get('/product-types', ProductController.getTypes);
router.post('/save-product-types', authMiddleware, adminMiddleware, ProductController.saveTypes);

export default router;